#!/usr/bin/env bash
# cloud-init user-data script
# Clones openclaw/openclaw from GitHub, builds it from source, and starts
# the gateway service on Ubuntu 22.04+.
# Rendered by Terraform — do not edit this file directly.

set -euo pipefail

OPENCLAW_REPO="https://github.com/openclaw/openclaw.git"
OPENCLAW_VERSION="${openclaw_version}"   # git ref: branch, tag or SHA (empty = main)
DOMAIN_NAME="${domain_name}"             # set for HTTPS; empty = HTTP only (not for production)
INSTALL_DIR="/opt/openclaw"
OPENCLAW_USER="openclaw"

log() { echo "[openclaw-install] $*" | tee -a /var/log/openclaw-install.log; }

log "Starting OpenClaw installation on Ubuntu"

# ── Wait for apt lock to be released (cloud-init can race with unattended-upgrades) ──
log "Waiting for apt lock"
while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 2; done

# ── System update ──────────────────────────────────────────────────────────────
log "Updating system packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get upgrade -y

# ── dependencies Install ────────────────────────────────────────────────
log "Installing git, curl, nginx"
apt-get install -y git curl nginx

# ── Install Node.js 22.x via NodeSource ──────────
log "Installing Node.js 22.x"
curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
apt-get install -y nodejs

log "Node version: $(node --version)"
log "npm version:  $(npm --version)"

# ── Enable pnpm Corepack via ────
log "Enabling pnpm via corepack"
corepack enable
corepack prepare pnpm@10.23.0 --activate

# ── Create a dedicated service user and install directory ──────────────────────
log "Creating install directory: $INSTALL_DIR"
mkdir -p "$INSTALL_DIR"

log "Creating system user: $OPENCLAW_USER"
id "$OPENCLAW_USER" &>/dev/null || \
  useradd --system --shell /bin/bash --no-create-home --home-dir "$INSTALL_DIR" "$OPENCLAW_USER"

# ── Clone openclaw/openclaw ────────────
log "Cloning $OPENCLAW_REPO"
if [ -d "$INSTALL_DIR/.git" ]; then
  log "Repository already exists — pulling latest"
  git -C "$INSTALL_DIR" fetch --prune
else
  git clone "$OPENCLAW_REPO" "$INSTALL_DIR"
fi

# Checkout a specific ref when requested
if [ -n "$OPENCLAW_VERSION" ]; then
  log "Checking out ref: $OPENCLAW_VERSION"
  git -C "$INSTALL_DIR" checkout "$OPENCLAW_VERSION"
else
  log "Using default branch (main)"
  git -C "$INSTALL_DIR" checkout main
  git -C "$INSTALL_DIR" pull --ff-only
fi

# ── Set ownership before running build steps ───────────────────────────────────
chown -R "$OPENCLAW_USER:$OPENCLAW_USER" "$INSTALL_DIR"

# ── Install npm dependencies and build as the service user ────────────────────
log "Running pnpm install"
sudo -u "$OPENCLAW_USER" bash -c "cd '$INSTALL_DIR' && pnpm install --frozen-lockfile"

log "Building OpenClaw (pnpm build)"
sudo -u "$OPENCLAW_USER" bash -c "cd '$INSTALL_DIR' && pnpm build"

# ── Create initial .env from example ──
if [ ! -f "$INSTALL_DIR/.env" ]; then
  log "Creating .env from .env.example"
  sudo -u "$OPENCLAW_USER" cp "$INSTALL_DIR/.env.example" "$INSTALL_DIR/.env"
  RANDOM_TOKEN=$(openssl rand -hex 32)
  sed -i "s|change-me-to-a-long-random-token|$RANDOM_TOKEN|" "$INSTALL_DIR/.env"
fi

# ── Create systemd service for OpenClaw gateway ──────────────
log "Creating openclaw-gateway systemd service"
cat > /etc/systemd/system/openclaw-gateway.service << 'SVCEOF'
[Unit]
Description=OpenClaw AI Gateway
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=openclaw
WorkingDirectory=/opt/openclaw
EnvironmentFile=/opt/openclaw/.env
ExecStart=/usr/bin/node /opt/openclaw/openclaw.mjs gateway --allow-unconfigured --bind lan
Restart=on-failure
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
SVCEOF

systemctl daemon-reload
systemctl enable --now openclaw-gateway

# ── Configure nginx as a reverse proxy ─────────────────────────────────────────
log "Configuring nginx reverse proxy"
cat > /etc/nginx/sites-available/openclaw << NGINXEOF
server {
    listen 80;
    server_name ${domain_name:-_};

    location / {
        proxy_pass http://127.0.0.1:18789;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_read_timeout 86400;
    }
}
NGINXEOF

ln -sf /etc/nginx/sites-available/openclaw /etc/nginx/sites-enabled/openclaw
rm -f /etc/nginx/sites-enabled/default
nginx -t && systemctl enable --now nginx

# ── Obtain TLS certificate via Let's Encrypt ───────────────────────────────────
if [ -n "$DOMAIN_NAME" ]; then
  log "Obtaining Let's Encrypt certificate for $DOMAIN_NAME"
  apt-get install -y certbot python3-certbot-nginx

  certbot --nginx \
    --non-interactive \
    --agree-tos \
    --email admin@lab86.work \
    --domains "$DOMAIN_NAME" \
    --redirect

  systemctl enable --now certbot.timer

  log "HTTPS enabled for $DOMAIN_NAME — nginx redirects HTTP → HTTPS"
else
  log "WARNING: domain_name not set — running HTTP only on port 80"
  log "WARNING: HTTPS is required for WhatsApp webhooks. Set var.domain_name and re-provision."
fi

log "OpenClaw installation complete"
log "Gateway: port 18789 (internal), proxied via nginx on port 80"
log ".env at: $INSTALL_DIR/.env — add API keys to enable AI providers"
